name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test
        run: mvn test
