name: Create release
run-name: Create release ${{ inputs.version }} on ${{ github.sha }} by @${{ github.actor }}

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        type: string
        description: 'Release version'
        required: false
      next:
        type: string
        description: 'Next development version'
        required: false

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CONDUKTORBOT_REPO_WRITE }}

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.CONDUKTOR_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "conduktorbot", "password": "${{ secrets.CONDUKTORBOT_GHCR_RW }}" }]'
          githubServer: false

      - name: Maven release prepare
        id: prepare
        run: |
          git config user.name "${{ steps.gpg.outputs.name }}"
          git config user.email "${{ steps.gpg.outputs.email }}"
          
          mvn --batch-mode release:prepare -DreleaseVersion=${{ env.RELEASE_VERSION }} -DdevelopmentVersion=${{ inputs.next }} -Dtag=${{ env.RELEASE_VERSION }} --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.CONDUKTORBOT_REPO_WRITE }}

  publish-release:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    steps:
      - name: Checkout tag ${{ env.RELEASE_VERSION }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "conduktorbot", "password": "${{ secrets.CONDUKTORBOT_GHCR_RW }}" }]'
          githubServer: false

      - name: Deploy
        run: mvn -DskipTests deploy

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.RELEASE_VERSION }}"
          tag: ${{ env.RELEASE_VERSION }}
          artifacts: "target/azure-kafka-oauthbearer-*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
