name: Publish release
run-name: Publish release ${{ github.ref_name }} on ${{ github.sha }} by @${{ github.actor }}

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check release version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
          else
            echo "Ref ${GITHUB_REF} is not a tag" 
            exit 1
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy
        run: mvn -DskipTests --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.RELEASE_VERSION }}"
          tag: ${{ env.RELEASE_VERSION }}
          artifacts: "target/azure-kafka-oauthbearer-*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
